quotation=p*max(wE,wT)
breakpointReferenceN=50
breakpointReferenceTotal=17135
breakpoint1=4283.75
breakpoint2=8567.5
defaultDiscountMarginalRates=1,0.85,0.70
defaultDiscountFileCount=1620
noDiscountFileCount=90
