outsourcingQuotation=lambda*p*max(wE,wT)
outsourcingBreakpointPolicy=fixed
outsourcingBreakpoint1=4000
outsourcingBreakpoint2=8000
outsourcingRates=0.5,1,2
discountMarginalRates=1,0.85,0.70
setupCostCoefficient=20
solveTimeLimitSeconds=10800
maxNodes=100000
discountModel=masterVariables
